name: Deploy to AWS using Terraform

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:   # This allows manual triggering from the GitHub UI

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "United States (N. Virginia)"  # Change to your desired region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.11"  # Or whatever version you prefer

      - name: Terraform Init
        run: terraform init terraform/

      - name: Terraform Plan
        run: terraform plan terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve terraform/
