name: Deploy Lambda Code

on:
  #push:
   # branches:
    #  - main  # Trigger when code changes are pushed to the main branch
  workflow_dispatch:   # This allows manual triggering from the GitHub UI

jobs:
  deploy_lambda_code:
    name: Deploy Lambda Code to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"  # Change to your desired region

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create Lambda Deployment Package
        run: |
          zip -r lambda_code.zip
          aws s3 cp lambda_code.zip s3://strbucket202512/lambda_code.zip

      - name: Trigger Lambda Update (Optional)
        run: |
          aws lambda update-function-code \
            --function-name "lambda_s3_trigger" \
            --s3-bucket "strbucket202512" \
            --s3-key "lambda_code.zip"
